sudo: false
os:
  - linux

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

notifications:
  email:
    on_success: never

script:
- ./ci/install_cargo_web.sh
- cargo build --verbose --all
- cargo test --verbose --all
- cargo bench --verbose --all
