sudo: false
os:
  - linux

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

notifications:
  email:
    on_success: never

script:
  - cargo build --verbose -p weave
  - cargo build --verbose -p ignition
  - cargo test --verbose -p weave
  - cargo test --verbose -p ignition
  - cargo bench --verbose -p weave
  - cargo bench --verbose -p ignition
  - ./ci/install_cargo_web.sh
  - cargo web build -p weave-visualizer
