[package]
name = "weave-lib"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]

[dependencies]


[dev-dependencies]
criterion = "0.2.4"

[[bench]]
name = "weave_bench"
harness = false
path = "benches/criterion/lib.rs"
